In [40]:
import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import certifi

In [41]:
# row 생략 없이 출력
pd.set_option('display.max_rows', None)
# col 생략 없이 출력
pd.set_option('display.max_columns', None)

In [42]:
auth_key = ''
# service_name = 'KeyStatisticList'
# service_name = 'StatisticItemList'
service_name = 'StatisticSearch'
language = 'kr'
res_format = 'json'
start_count = '1'
end_count = '99999'
# table_code = ''
# start_time = ''
# end_time = ''
# item_code = ''


# url service_name/sample/json(xml)/kr(en)/start_no/end_no/table_code/time_period/search_from/search_end/item_code
# url = f'http://ecos.bok.or.kr/api/{service_name}/{auth_key}/{res_format}/{language}/1/100/802Y001/D/20000101/20000130/'

In [43]:
class Ecos:
    def __init__(self, auth_key):
        self.auth = auth_key
        self.base_url = 'http://ecos.bok.or.kr/api'
    
    def get_static_table_list(self, static_code=None):
        if static_code is None:
            static_code = ''
        param_list = [
            'StatisticTableList',
            self.auth,
            res_format,
            language,
            start_count,
            end_count,
            static_code
        ]
        param_url = '/'.join(param_list)
        url = f'{self.base_url}/{param_url}'
        res = requests.get(url)
        if res.status_code == 200:
            result = res.json()
            # print(result)
        else:
            print('request failed:', res.status_code)
        df = pd.DataFrame(result['StatisticTableList']['row'])
        return df
    
    def get_static_word(self, word):
        param_list = [
            'StatisticWord',
            self.auth,
            res_format,
            language,
            start_count,
            end_count,
            word
        ]
        param_url = '/'.join(param_list)
        url = f'{self.base_url}/{param_url}'
        res = requests.get(url)
        if res.status_code == 200:
            result = res.json()
            # print(result)
        else:
            print('request failed:', res.status_code)
        df = pd.DataFrame(result['StatisticWord']['row'])
        return df
    
    def get_static_item_list(self, static_code):
        param_list = [
            'StatisticItemList',
            self.auth,
            res_format,
            language,
            start_count,
            end_count,
            static_code
        ]
        param_url = '/'.join(param_list)
        url = f'{self.base_url}/{param_url}'
        res = requests.get(url)
        if res.status_code == 200:
            result = res.json()
            # print(result)
        else:
            print('request failed:', res.status_code)
        df = pd.DataFrame(result['StatisticItemList']['row'])
        return df
    
    def get_static_serch(self, static_code, period, start_time, end_time, item_code1=None, item_code2=None, item_code3=None, item_code4=None):
        if item_code1 is None:
            item_code1 = ''
        if item_code2 is None:
            item_code2 = ''
        if item_code3 is None:
            item_code3 = ''
        if item_code4 is None:
            item_code4 = ''
        
        param_list = [
            'StatisticSearch',
            self.auth,
            res_format,
            language,
            start_count,
            end_count,
            static_code,
            period,
            start_time,
            end_time,
            item_code1,
            item_code2,
            item_code3,
            item_code4
        ]
        param_url = '/'.join(param_list)
        url = f'{self.base_url}/{param_url}'
        res = requests.get(url)
        if res.status_code == 200:
            result = res.json()
            # print(result)
        else:
            print('request failed:', res.status_code)
        df = pd.DataFrame(result['StatisticSearch']['row'])
        return df
    
    def get_key_statistic_list(self):
        param_list = [
            'KeyStatisticList',
            self.auth,
            res_format,
            language,
            start_count,
            '100'
        ]
        param_url = '/'.join(param_list)
        url = f'{self.base_url}/{param_url}'
        res = requests.get(url)
        if res.status_code == 200:
            result = res.json()
            # print(result)
        else:
            print('request failed:', res.status_code)
        df = pd.DataFrame(result['KeyStatisticList']['row'])
        return df

In [70]:
ecos_api = Ecos(auth_key)
# df = ecos_api.get_static_table_list()
# df = df.loc[df['SRCH_YN'] == 'Y', :]
# df = ecos_api.get_static_word('소비자동향지수')
df = ecos_api.get_static_item_list('902Y017')
# df = ecos_api.get_static_serch('802Y001', 'D', '20240101', '20240610', '0001000')
# df = ecos_api.get_key_statistic_list()
# df = df.loc[df['CYCLE'] == 'D', :]
df

,STAT_CODE,STAT_NAME,GRP_CODE,GRP_NAME,ITEM_CODE,ITEM_NAME,P_ITEM_CODE,P_ITEM_NAME,CYCLE,START_TIME,END_TIME,DATA_CNT,UNIT_NAME,WEIGHT
0,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,KOR,한국,None,None,A,1953,2022,70,백만달러,None
1,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,AUS,호주,None,None,A,1959,2022,64,백만달러,None
2,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,AUT,오스트리아,None,None,A,1970,2022,53,백만달러,None
3,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,BEL,벨기에,None,None,A,1970,2022,53,백만달러,None
4,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,CAN,캐나다,None,None,A,1970,2023,54,백만달러,None
5,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,CHL,칠레,None,None,A,1996,2022,27,백만달러,None
6,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,CHN,중국,None,None,A,1978,2022,45,백만달러,None
7,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,CZE,체코,None,None,A,1992,2022,31,백만달러,None
8,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,DNK,덴마크,None,None,A,1966,2022,57,백만달러,None
9,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,EST,에스토니아,None,None,A,2000,2022,23,백만달러,None
10,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,FIN,핀란드,None,None,A,1970,2023,54,백만달러,None
11,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,FRA,프랑스,None,None,A,1950,2022,73,백만달러,None
12,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,DEU,독일,None,None,A,1970,2023,54,백만달러,None
13,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,GRC,그리스,None,None,A,2006,2022,17,백만달러,None
14,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,HUN,헝가리,None,None,A,1993,2022,30,백만달러,None
15,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,IRL,아일랜드,None,None,A,1970,2022,53,백만달러,None
16,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,ISR,이스라엘,None,None,A,1970,2022,53,백만달러,None
17,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,ITA,이탈리아,None,None,A,1970,2023,54,백만달러,None
18,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,JPN,일본,None,None,A,1970,2022,53,백만달러,None
19,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,LVA,라트비아,None,None,A,1995,2022,28,백만달러,None
20,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,LUX,룩셈부르크,None,None,A,1970,2022,53,백만달러,None
21,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,MEX,멕시코,None,None,A,1970,2022,53,백만달러,None
22,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,NLD,네덜란드,None,None,A,1969,2022,54,백만달러,None
23,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,NZL,뉴질랜드,None,None,A,1970,2022,53,백만달러,None
24,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,NOR,노르웨이,None,None,A,1970,2022,53,백만달러,None
25,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,POL,폴란드,None,None,A,1991,2022,32,백만달러,None
26,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,PRT,포르투갈,None,None,A,1970,2023,54,백만달러,None
27,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,RUS,러시아,None,None,A,1993,2020,28,백만달러,None
28,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,SVK,슬로바키아,None,None,A,1995,2023,29,백만달러,None
29,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,SVN,슬로베니아,None,None,A,1995,2022,28,백만달러,None
30,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,ESP,스페인,None,None,A,1970,2022,53,백만달러,None
31,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,SWE,스웨덴,None,None,A,1970,2023,54,백만달러,None
32,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,CHE,스위스,None,None,A,1995,2022,28,백만달러,None
33,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,TUR,튀르키예,None,None,A,2009,2017,9,백만달러,None
34,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,GBR,영국,None,None,A,1970,2023,54,백만달러,None
35,902Y017,9.1.4.4. 국제 주요국 국민총소득(GNI),Group1,계정항목,USA,미국,None,None,A,1970,2022,53,백만달러,None

In [47]:
df_d = df.loc[df['CYCLE'] == 'D', :]
df_d

,P_STAT_CODE,STAT_CODE,STAT_NAME,CYCLE,SRCH_YN,ORG_NAME
101,0000000048,722Y001,1.3.1. 한국은행 기준금리 및 여수신금리,D,Y,None
103,0000000050,817Y002,1.3.2.1. 시장금리(일별),D,Y,한국은행
128,0000000398,802Y001,1.5.1.1. 주식시장(일),D,Y,한국거래소(051-662-2000)
527,0000000178,731Y001,3.1.1.1. 주요국 통화의 대원화환율,D,Y,서울외국환중개
528,0000000178,731Y002,3.1.1.2. 주요국 통화의 대미달러환율,D,Y,서울외국환중개
529,0000000178,731Y003,"3.1.1.3. 원화의 대미달러, 원화의 대위안/대엔 환율",D,Y,한국은행
747,0000000283,521Y001,6.4. 뉴스심리지수(실험적 통계),D,Y,None